import React from 'react'
export const metadata = {
  title: "SIGN IN    ",
  description: "Generated by create next app",

};
const Signin = () => {
  return (
    <div>
      Signin
    </div>
  )
}

export default Signin
