import Header from "@/components/header/Header";
import React from "react";
import RegisterForm from "./RegisterForm";

export const metadata = {
  title: "REGISTER    ",
  description: "Generated by create next app",
};

const Register = () => {
  return (
    <>
      <Header isRegisterPage={true} />

      <main className="px-3">
       <RegisterForm/>
      </main>
    </>
  );
};

export default Register;
