import React from 'react'
export const metadata = {
  title: "CART",
  description: "Generated by create next app",

};
const Cart = () => {
  return (
    <div>
      cart
    </div>
  )
}

export default Cart
