import React from 'react'
export const metadata = {
  title: "REGISTER    ",
  description: "Generated by create next app",

};
const Register = () => {
  return (
    <div>
      Register
    </div>
  )
}

export default Register
